Repository awesome-cis/take_break, pull requests merged in 2019-07, with the labels that each got.

#71 path alias 설정
  take_break_client/next.config.js
  take_break_client/src/components/Register/RegisterForm.tsx
Labels: enhancement

#73 기본 types 생성
  take_break_client/src/types/Basic.ts
  take_break_client/src/types/Invite.ts
  take_break_client/src/types/Member.ts
  take_break_client/src/types/Organization.ts
  take_break_client/src/types/User.ts
  take_break_client/src/types/Vacation.ts
  take_break_client/src/types/VacationCount.ts
Labels: type

#70 UserServiceAgent 추가
  take_break_client/src/agent/UserServiceAgent.ts
  take_break_client/src/agent/index.ts
  take_break_client/src/components/Register/RegisterForm.tsx
Labels: enhancement

#72 env 파일 환경별로 분리
  .gitignore
  take_break_client/.env.sample
  take_break_server/.env.sample
  take_break_server/README.md
  take_break_server/app.ts
  take_break_server/config/.env.development
  take_break_server/config/.env.local.sample
  take_break_server/config/.env.production.sample
  take_break_server/config/.env.test
  take_break_server/config/config.js
  take_break_server/database/db.ts
  take_break_server/init.ts
  take_break_server/initEnv.js
Labels: enhancement

#79 auth store 생성
  take_break_client/pages/_app.tsx
  take_break_client/src/store/auth/actionTypes.ts
  take_break_client/src/store/auth/actions.ts
  take_break_client/src/store/auth/reducers.ts
  take_break_client/src/store/auth/types.ts
  take_break_client/src/store/index.ts
Labels: feature
