Repository awesome-cis/take_break, pull requests merged in 2019-06, with the labels that each got.

#15 Letsget23/code integration
  .gitignore
  README.md
  server/server.ts
  take_break_client/.babelrc
  take_break_client/.storybook/addons.ts
  take_break_client/.storybook/config.ts
  take_break_client/.storybook/webpack.config.js
  take_break_client/READMD.md
  take_break_client/next.config.js
  take_break_client/nodemon.json
  take_break_client/package-lock.json
  take_break_client/package.json
  take_break_client/pages/_app.tsx
  take_break_client/pages/index.tsx
  take_break_client/pages/login.tsx
  take_break_client/server/server.ts
  take_break_client/src/components/Login/Login.tsx
  take_break_client/src/components/Login/LoginForm/LoginForm.tsx
  take_break_client/src/components/Login/LoginForm/index.tsx
  take_break_client/src/components/Login/LoginForm/styles.scss
  take_break_client/src/components/Login/LoginInfo/LoginInfo.tsx
  take_break_client/src/components/Login/LoginInfo/index.tsx
  take_break_client/src/components/Login/LoginInfo/styles.scss
  take_break_client/src/components/Login/index.tsx
  take_break_client/src/components/Login/styles.scss
  take_break_client/src/styles/ant.less
  take_break_client/src/styles/app.scss
  take_break_client/src/styles/index.scss
  take_break_client/stories/index.tsx
  take_break_client/tsconfig.json
  take_break_client/tsconfig.server.json
  take_break_client/tslint.json
  take_break_server/.env.sample
  take_break_server/app.js
  take_break_server/database/db.js
  take_break_server/models/user.js
  take_break_server/package-lock.json
  take_break_server/package.json
  take_break_server/routes/auth.js
  take_break_server/routes/index.js
  take_break_server/routes/middlewares/authMiddleware.js
  take_break_server/routes/users.js
Labels: setting

#21 (Base #19) set basic test for server
  take_break_server/@types/index.d.ts
  take_break_server/app.ts
  take_break_server/database/db.ts
  take_break_server/jest.config.js
  take_break_server/models/user.ts
  take_break_server/package-lock.json
  take_break_server/package.json
  take_break_server/prepareDatabase.ts
  take_break_server/routes/auth.ts
  take_break_server/routes/index.ts
  take_break_server/test/index.test.ts
  take_break_server/test/routes/auth.test.ts
  take_break_server/test/routes/index.test.ts
  take_break_server/tsconfig.json
Labels: WIP, feature

#19 (Base #17) apply typescript to API Server
  README.md
  take_break_server/@types/index.d.ts
  take_break_server/app.js
  take_break_server/app.ts
  take_break_server/database/db.js
  take_break_server/database/db.ts
  take_break_server/init.ts
  take_break_server/jest.config.js
  take_break_server/lib/PasswordUtil.js
  take_break_server/lib/PasswordUtil.ts
  take_break_server/models/user.js
  take_break_server/models/user.ts
  take_break_server/package-lock.json
  take_break_server/package.json
  take_break_server/passport/index.js
  take_break_server/passport/index.ts
  take_break_server/passport/localStrategy.ts
  take_break_server/prepareDatabase.ts
  take_break_server/routes/auth.js
  take_break_server/routes/auth.ts
  take_break_server/routes/index.js
  take_break_server/routes/index.ts
  take_break_server/routes/middlewares/authMiddleware.ts
  take_break_server/routes/users.js
  take_break_server/routes/users.ts
  take_break_server/test/index.test.ts
  take_break_server/test/routes/auth.test.ts
  take_break_server/test/routes/index.test.ts
  take_break_server/tsconfig.json
  take_break_server/webpack.config.js
Labels: setting

#28 (Base #27) Change model import method
  take_break_server/app.ts
  take_break_server/models/index.ts
  take_break_server/models/invite.ts
  take_break_server/models/organization.ts
  take_break_server/models/user.ts
  take_break_server/models/vacation.ts
  take_break_server/passport/localStrategy.ts
  take_break_server/routes/auth.ts
  take_break_server/routes/middlewares/authMiddleware.ts
  take_break_server/test/routes/auth.test.ts
Labels: enhancement

#27 Database migration by shell cmd
  README.md
  take_break_server/.env.sample
  take_break_server/.sequelizerc
  take_break_server/README.md
  take_break_server/app.ts
  take_break_server/config/config.js
  take_break_server/config/migrationColumns.ts
  take_break_server/database/db.ts
  take_break_server/migrations/20190605153124-create-users.js
  take_break_server/migrations/20190606014542-create-invites.js
  take_break_server/migrations/20190606014847-create-organizations.js
  take_break_server/migrations/20190606014941-create-vacation-counts.js
  take_break_server/migrations/20190606015208-create-vacations.js
  take_break_server/models/index.ts
  take_break_server/models/invite.ts
  take_break_server/models/organization.ts
  take_break_server/models/user.ts
  take_break_server/models/vacation.ts
  take_break_server/models/vacationCount.ts
  take_break_server/package-lock.json
  take_break_server/package.json
  take_break_server/passport/localStrategy.ts
  take_break_server/prepareDatabase.ts
  take_break_server/routes/auth.ts
  take_break_server/routes/middlewares/authMiddleware.ts
  take_break_server/test/routes/auth.test.ts
Labels: enhancement, setting

#37 (Base #36) fix new Sequelize parameter order
  .gitignore
  take_break_client/.env
  take_break_client/.env.sample
  take_break_client/agent/agent.ts
  take_break_client/agent/index.ts
  take_break_client/next.config.js
  take_break_client/package-lock.json
  take_break_client/package.json
  take_break_client/pages/index.tsx
  take_break_client/server/init.ts
  take_break_client/server/server.ts
  take_break_server/config/migrationColumns.js
  take_break_server/database/db.ts
  take_break_server/package-lock.json
  take_break_server/package.json
  take_break_server/routes/auth.ts
  take_break_server/webpack.config.js
Labels: bugfix

#36 sequelize db:migrate error
  .gitignore
  take_break_client/.env
  take_break_client/.env.sample
  take_break_client/agent/agent.ts
  take_break_client/agent/index.ts
  take_break_client/next.config.js
  take_break_client/package-lock.json
  take_break_client/package.json
  take_break_client/pages/index.tsx
  take_break_client/server/init.ts
  take_break_client/server/server.ts
  take_break_server/config/migrationColumns.js
  take_break_server/database/db.ts
  take_break_server/package-lock.json
  take_break_server/package.json
  take_break_server/routes/auth.ts
  take_break_server/webpack.config.js
Labels: bugfix

#29 회원가입 UI 작업
  take_break_client/package-lock.json
  take_break_client/pages/register.tsx
  take_break_client/src/components/Login/LoginForm/LoginForm.tsx
  take_break_client/src/components/Register/Register.tsx
  take_break_client/src/components/Register/RegisterForm.tsx
  take_break_client/src/components/Register/index.tsx
  take_break_client/src/components/Register/styles.scss
Labels: style

#45 (Base #43) Organization 생성/삭제 API
  take_break_server/README.md
  take_break_server/app.ts
  take_break_server/models/organization.ts
  take_break_server/package.json
  take_break_server/routes/organizations.ts
  take_break_server/test/routes/organizations.test.ts
Labels: feature

#43 API, 라이브러리 관련 세팅 수정
  take_break_server/README.md
  take_break_server/app.ts
  take_break_server/database/db.ts
  take_break_server/models/organization.ts
  take_break_server/package.json
  take_break_server/routes/auth.ts
  take_break_server/routes/middlewares/authMiddleware.ts
  take_break_server/routes/organizations.ts
  take_break_server/routes/users.ts
  take_break_server/test/routes/organizations.test.ts
Labels: bugfix, setting

#57 initialize Redux
  take_break_client/package-lock.json
  take_break_client/package.json
  take_break_client/pages/_app.tsx
  take_break_client/pages/redux.tsx
  take_break_client/store/calculator/actions.ts
  take_break_client/store/calculator/reducers.ts
  take_break_client/store/calculator/types.ts
  take_break_client/store/index.ts
Labels: feature

#59 redux-actions 사용 및 올바른 타입핑 처리
  take_break_client/pages/redux.tsx
  take_break_client/store/calculator/actions.ts
  take_break_client/store/calculator/reducers.ts
  take_break_client/store/calculator/types.ts
Labels: enhancement

#51 (Base #50) 조직API 라우트 에러 핸들링
  take_break_server/app.ts
  take_break_server/constants/index.ts
  take_break_server/factories/organizationFactory.ts
  take_break_server/lib/errors/APIError.ts
  take_break_server/migrations/20190606014847-create-organizations.js
  take_break_server/models/organization.ts
  take_break_server/routes/auth.ts
  take_break_server/routes/errorMiddlewares/apiErrorMiddleware.ts
  take_break_server/routes/middlewares/authMiddleware.ts
  take_break_server/routes/organizations.ts
  take_break_server/test/routes/auth.test.ts
  take_break_server/test/routes/organizations.test.ts
Labels: enhancement

#50 (Base #48) Sequelize paranoid 옵션 적용
  take_break_server/app.ts
  take_break_server/config/migrationColumns.js
  take_break_server/config/migrationOptions.js
  take_break_server/constants/index.ts
  take_break_server/factories/organizationFactory.ts
  take_break_server/lib/errors/APIError.ts
  take_break_server/migrations/20190606014847-create-organizations.js
  take_break_server/models/invite.ts
  take_break_server/models/organization.ts
  take_break_server/models/user.ts
  take_break_server/models/vacation.ts
  take_break_server/models/vacationCount.ts
  take_break_server/routes/auth.ts
  take_break_server/routes/errorMiddlewares/apiErrorMiddleware.ts
  take_break_server/routes/middlewares/authMiddleware.ts
  take_break_server/routes/organizations.ts
  take_break_server/test/routes/auth.test.ts
  take_break_server/test/routes/organizations.test.ts
Labels: enhancement

#48 (Base #47) 테스트 리팩토링
  take_break_server/app.ts
  take_break_server/config/migrationColumns.js
  take_break_server/config/migrationOptions.js
  take_break_server/constants/index.ts
  take_break_server/factories/organizationFactory.ts
  take_break_server/lib/errors/APIError.ts
  take_break_server/migrations/20190606014847-create-organizations.js
  take_break_server/models/invite.ts
  take_break_server/models/organization.ts
  take_break_server/models/user.ts
  take_break_server/models/vacation.ts
  take_break_server/models/vacationCount.ts
  take_break_server/routes/auth.ts
  take_break_server/routes/errorMiddlewares/apiErrorMiddleware.ts
  take_break_server/routes/middlewares/authMiddleware.ts
  take_break_server/routes/organizations.ts
  take_break_server/test/index.test.ts
  take_break_server/test/routes/auth.test.ts
  take_break_server/test/routes/index.test.ts
  take_break_server/test/routes/organizations.test.ts
Labels: enhancement

#47 테스트에 모델 팩토리 적용
  take_break_server/app.ts
  take_break_server/config/migrationColumns.js
  take_break_server/config/migrationOptions.js
  take_break_server/constants/index.ts
  take_break_server/factories/index.ts
  take_break_server/factories/organizationFactory.ts
  take_break_server/factories/userFactory.ts
  take_break_server/lib/errors/APIError.ts
  take_break_server/migrations/20190606014847-create-organizations.js
  take_break_server/models/invite.ts
  take_break_server/models/organization.ts
  take_break_server/models/user.ts
  take_break_server/models/vacation.ts
  take_break_server/models/vacationCount.ts
  take_break_server/package-lock.json
  take_break_server/package.json
  take_break_server/routes/auth.ts
  take_break_server/routes/errorMiddlewares/apiErrorMiddleware.ts
  take_break_server/routes/middlewares/authMiddleware.ts
  take_break_server/routes/organizations.ts
  take_break_server/test/index.test.ts
  take_break_server/test/routes/auth.test.ts
  take_break_server/test/routes/index.test.ts
  take_break_server/test/routes/organizations.test.ts
Labels: enhancement

#64 회원 가입 로직 추가
  take_break_client/agent/agent.ts
  take_break_client/pages/index.tsx
  take_break_client/src/components/Register/RegisterForm.tsx
  take_break_server/migrations/20190605153124-create-users.js
  take_break_server/models/user.ts
  take_break_server/package-lock.json
  take_break_server/routes/auth.ts
  take_break_server/test/routes/auth.test.ts
Labels: enhancement
